[2025-05-02T17:47:56.875+0000] {processor.py:157} INFO - Started process (PID=163) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-02T17:47:56.877+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-02T17:47:56.880+0000] {logging_mixin.py:150} INFO - [2025-05-02T17:47:56.879+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-02T17:47:56.940+0000] {logging_mixin.py:150} INFO - [2025-05-02T17:47:56.930+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 6, in <module>
    from load_teams import load_teams_data
ModuleNotFoundError: No module named 'load_teams'
[2025-05-02T17:47:56.943+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-02T17:47:56.998+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.131 seconds
[2025-05-02T17:48:27.200+0000] {processor.py:157} INFO - Started process (PID=168) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-02T17:48:27.203+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-02T17:48:27.206+0000] {logging_mixin.py:150} INFO - [2025-05-02T17:48:27.205+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-02T17:48:27.239+0000] {logging_mixin.py:150} INFO - [2025-05-02T17:48:27.233+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 6, in <module>
    from load_teams import load_teams_data
ModuleNotFoundError: No module named 'load_teams'
[2025-05-02T17:48:27.242+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-02T17:48:27.292+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.101 seconds
[2025-05-02T17:48:57.432+0000] {processor.py:157} INFO - Started process (PID=173) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-02T17:48:57.434+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-02T17:48:57.438+0000] {logging_mixin.py:150} INFO - [2025-05-02T17:48:57.437+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-02T17:48:57.480+0000] {logging_mixin.py:150} INFO - [2025-05-02T17:48:57.472+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 6, in <module>
    from load_teams import load_teams_data
ModuleNotFoundError: No module named 'load_teams'
[2025-05-02T17:48:57.484+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-02T17:48:57.552+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.130 seconds
[2025-05-02T17:49:28.333+0000] {processor.py:157} INFO - Started process (PID=178) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-02T17:49:28.336+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-02T17:49:28.338+0000] {logging_mixin.py:150} INFO - [2025-05-02T17:49:28.337+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-02T17:49:28.375+0000] {logging_mixin.py:150} INFO - [2025-05-02T17:49:28.368+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 6, in <module>
    from load_teams import load_teams_data
ModuleNotFoundError: No module named 'load_teams'
[2025-05-02T17:49:28.377+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-02T17:49:28.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.095 seconds
[2025-05-02T17:49:59.307+0000] {processor.py:157} INFO - Started process (PID=183) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-02T17:49:59.310+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-02T17:49:59.313+0000] {logging_mixin.py:150} INFO - [2025-05-02T17:49:59.311+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-02T17:49:59.342+0000] {logging_mixin.py:150} INFO - [2025-05-02T17:49:59.337+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 6, in <module>
    from load_teams import load_teams_data
ModuleNotFoundError: No module named 'load_teams'
[2025-05-02T17:49:59.344+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-02T17:49:59.385+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.085 seconds
