[2025-05-07T09:04:34.912+0000] {processor.py:157} INFO - Started process (PID=185) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:04:34.918+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:04:34.936+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:04:34.927+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:04:35.071+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:04:35.032+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 6, in <module>
    from load_teams import load_teams_data
ModuleNotFoundError: No module named 'load_teams'
[2025-05-07T09:04:35.075+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:04:35.229+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.386 seconds
[2025-05-07T09:05:05.583+0000] {processor.py:157} INFO - Started process (PID=190) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:05:05.587+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:05:05.589+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:05:05.589+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:05:05.626+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:05:05.619+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 6, in <module>
    from load_teams import load_teams_data
ModuleNotFoundError: No module named 'load_teams'
[2025-05-07T09:05:05.627+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:05:05.672+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.095 seconds
[2025-05-07T09:05:35.831+0000] {processor.py:157} INFO - Started process (PID=195) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:05:35.833+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:05:35.835+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:05:35.834+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:05:35.870+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:05:35.864+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 6, in <module>
    from load_teams import load_teams_data
ModuleNotFoundError: No module named 'load_teams'
[2025-05-07T09:05:35.872+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:05:35.918+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.092 seconds
[2025-05-07T09:06:06.847+0000] {processor.py:157} INFO - Started process (PID=200) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:06:06.849+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:06:06.850+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:06:06.850+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:06:06.884+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:06:06.878+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 6, in <module>
    from load_teams import load_teams_data
ModuleNotFoundError: No module named 'load_teams'
[2025-05-07T09:06:06.886+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:06:06.930+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.087 seconds
[2025-05-07T09:06:37.095+0000] {processor.py:157} INFO - Started process (PID=205) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:06:37.098+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:06:37.100+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:06:37.099+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:06:37.128+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:06:37.123+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 6, in <module>
    from load_teams import load_teams_data
ModuleNotFoundError: No module named 'load_teams'
[2025-05-07T09:06:37.130+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:06:37.176+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.087 seconds
[2025-05-07T09:07:07.340+0000] {processor.py:157} INFO - Started process (PID=210) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:07.343+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:07:07.344+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:07:07.344+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:07.383+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:07:07.376+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 6, in <module>
    from load_teams import load_teams_data
ModuleNotFoundError: No module named 'load_teams'
[2025-05-07T09:07:07.385+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:07.429+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.095 seconds
[2025-05-07T09:07:37.507+0000] {processor.py:157} INFO - Started process (PID=215) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:37.513+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:07:37.517+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:07:37.516+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:37.556+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:07:37.547+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 6, in <module>
    from load_teams import load_teams_data
ModuleNotFoundError: No module named 'load_teams'
[2025-05-07T09:07:37.559+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:37.623+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.128 seconds
[2025-05-07T09:07:55.801+0000] {processor.py:157} INFO - Started process (PID=220) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:55.808+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:07:55.818+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:07:55.816+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:56.161+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:07:56.067+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:07:56.177+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:56.456+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.681 seconds
[2025-05-07T09:07:56.779+0000] {processor.py:157} INFO - Started process (PID=225) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:56.820+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:07:56.829+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:07:56.827+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:56.908+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:07:56.893+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:07:56.912+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:57.005+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.307 seconds
[2025-05-07T09:07:57.136+0000] {processor.py:157} INFO - Started process (PID=230) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:57.141+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:07:57.143+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:07:57.143+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:57.210+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:07:57.196+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:07:57.214+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:57.341+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.216 seconds
[2025-05-07T09:07:57.501+0000] {processor.py:157} INFO - Started process (PID=235) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:57.507+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:07:57.511+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:07:57.510+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:57.623+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:07:57.593+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:07:57.628+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:57.747+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.262 seconds
[2025-05-07T09:07:58.002+0000] {processor.py:157} INFO - Started process (PID=240) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:58.016+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:07:58.030+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:07:58.029+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:58.266+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:07:58.209+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:07:58.282+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:58.495+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.514 seconds
[2025-05-07T09:07:59.170+0000] {processor.py:157} INFO - Started process (PID=245) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:07:59.195+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:07:59.237+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:07:59.229+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:08:00.133+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:07:59.859+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:08:00.152+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:08:00.332+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 1.185 seconds
[2025-05-07T09:08:30.576+0000] {processor.py:157} INFO - Started process (PID=250) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:08:30.579+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:08:30.581+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:08:30.581+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:08:30.616+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:08:30.610+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:08:30.618+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:08:30.660+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.091 seconds
[2025-05-07T09:09:00.753+0000] {processor.py:157} INFO - Started process (PID=255) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:09:00.755+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:09:00.757+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:09:00.756+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:09:00.790+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:09:00.783+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:09:00.793+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:09:00.842+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.096 seconds
[2025-05-07T09:09:31.844+0000] {processor.py:157} INFO - Started process (PID=260) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:09:31.847+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:09:31.849+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:09:31.848+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:09:31.890+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:09:31.881+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:09:31.892+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:09:31.949+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.113 seconds
[2025-05-07T09:10:02.140+0000] {processor.py:157} INFO - Started process (PID=271) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:10:02.142+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:10:02.150+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:10:02.149+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:10:02.217+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:10:02.202+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:10:02.221+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:10:02.310+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.178 seconds
[2025-05-07T09:10:32.442+0000] {processor.py:157} INFO - Started process (PID=276) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:10:32.446+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:10:32.449+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:10:32.448+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:10:32.506+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:10:32.494+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:10:32.509+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:10:32.569+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.137 seconds
[2025-05-07T09:11:02.757+0000] {processor.py:157} INFO - Started process (PID=281) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:11:02.759+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:11:02.762+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:11:02.761+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:11:02.804+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:11:02.796+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:11:02.809+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:11:02.863+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.115 seconds
[2025-05-07T09:11:32.960+0000] {processor.py:157} INFO - Started process (PID=286) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:11:32.963+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:11:32.967+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:11:32.966+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:11:33.029+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:11:33.018+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:11:33.033+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:11:33.107+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.159 seconds
[2025-05-07T09:12:03.352+0000] {processor.py:157} INFO - Started process (PID=291) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:12:03.356+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:12:03.360+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:12:03.359+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:12:03.430+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:12:03.417+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:12:03.433+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:12:03.539+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.198 seconds
[2025-05-07T09:12:33.647+0000] {processor.py:157} INFO - Started process (PID=296) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:12:33.651+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:12:33.654+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:12:33.653+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:12:33.682+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:12:33.677+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:12:33.684+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:12:33.719+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.083 seconds
[2025-05-07T09:13:03.898+0000] {processor.py:157} INFO - Started process (PID=301) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:13:03.900+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:13:03.903+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:13:03.902+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:13:03.934+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:13:03.928+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:13:03.937+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:13:03.975+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.081 seconds
[2025-05-07T09:13:34.107+0000] {processor.py:157} INFO - Started process (PID=306) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:13:34.109+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:13:34.113+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:13:34.112+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:13:34.176+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:13:34.164+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:13:34.181+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:13:34.296+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.203 seconds
[2025-05-07T09:14:04.568+0000] {processor.py:157} INFO - Started process (PID=311) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:14:04.570+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:14:04.572+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:14:04.572+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:14:04.617+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:14:04.609+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:14:04.619+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:14:04.668+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.107 seconds
[2025-05-07T09:14:34.772+0000] {processor.py:157} INFO - Started process (PID=316) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:14:34.775+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:14:34.777+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:14:34.776+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:14:34.813+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:14:34.804+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:14:34.815+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:14:34.853+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.087 seconds
[2025-05-07T09:15:05.004+0000] {processor.py:157} INFO - Started process (PID=321) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:15:05.006+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:15:05.007+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:15:05.007+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:15:05.031+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:15:05.026+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:15:05.033+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:15:05.069+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.071 seconds
[2025-05-07T09:15:35.253+0000] {processor.py:157} INFO - Started process (PID=326) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:15:35.255+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:15:35.258+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:15:35.257+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:15:35.300+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:15:35.292+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:15:35.303+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:15:35.348+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.104 seconds
[2025-05-07T09:16:05.805+0000] {processor.py:157} INFO - Started process (PID=331) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:16:05.807+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:16:05.809+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:16:05.808+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:16:05.849+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:16:05.841+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:16:05.853+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:16:05.903+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.105 seconds
[2025-05-07T09:16:36.250+0000] {processor.py:157} INFO - Started process (PID=336) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:16:36.252+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:16:36.253+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:16:36.253+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:16:36.284+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:16:36.279+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:16:36.286+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:16:36.318+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.073 seconds
[2025-05-07T09:17:06.475+0000] {processor.py:157} INFO - Started process (PID=341) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:17:06.477+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:17:06.478+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:17:06.478+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:17:06.509+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:17:06.503+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:17:06.510+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:17:06.545+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.073 seconds
[2025-05-07T09:17:36.612+0000] {processor.py:157} INFO - Started process (PID=346) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:17:36.613+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:17:36.615+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:17:36.615+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:17:36.650+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:17:36.642+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:17:36.653+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:17:36.696+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.092 seconds
[2025-05-07T09:18:07.309+0000] {processor.py:157} INFO - Started process (PID=351) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:18:07.312+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:18:07.314+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:18:07.313+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:18:02.443+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:18:02.434+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:18:02.446+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:18:02.502+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.126 seconds
[2025-05-07T09:18:32.602+0000] {processor.py:157} INFO - Started process (PID=356) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:18:32.604+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:18:32.606+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:18:32.606+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:18:32.646+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:18:32.639+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:18:32.648+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:18:32.689+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.093 seconds
[2025-05-07T09:19:03.500+0000] {processor.py:157} INFO - Started process (PID=361) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:19:03.505+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:19:03.508+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:19:03.507+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:19:03.539+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:19:03.534+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:19:03.541+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:19:03.579+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.084 seconds
[2025-05-07T09:19:34.224+0000] {processor.py:157} INFO - Started process (PID=366) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:19:34.226+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:19:34.228+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:19:34.228+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:19:34.266+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:19:34.260+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:19:34.267+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:19:34.308+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.090 seconds
[2025-05-07T09:20:04.503+0000] {processor.py:157} INFO - Started process (PID=371) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:20:04.506+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:20:04.509+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:20:04.508+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:20:04.559+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:20:04.550+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:20:04.563+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:20:04.625+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.129 seconds
[2025-05-07T09:22:26.744+0000] {processor.py:157} INFO - Started process (PID=162) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:22:26.748+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:22:26.751+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:22:26.751+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:22:26.829+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:22:26.808+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:22:26.833+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:22:26.948+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.218 seconds
[2025-05-07T09:22:57.085+0000] {processor.py:157} INFO - Started process (PID=168) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:22:57.088+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:22:57.090+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:22:57.089+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:22:57.125+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:22:57.117+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:22:57.128+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:22:57.187+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.111 seconds
[2025-05-07T09:23:28.198+0000] {processor.py:157} INFO - Started process (PID=173) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:23:28.200+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:23:28.202+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:23:28.201+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:23:28.230+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:23:28.224+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:23:28.232+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:23:28.270+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.080 seconds
[2025-05-07T09:23:58.331+0000] {processor.py:157} INFO - Started process (PID=178) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:23:58.333+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:23:58.335+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:23:58.335+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:23:58.364+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:23:58.358+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:23:58.365+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:23:58.402+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.077 seconds
[2025-05-07T09:24:28.456+0000] {processor.py:157} INFO - Started process (PID=183) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:24:28.458+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:24:28.459+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:24:28.459+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:24:28.491+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:24:28.483+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:24:28.493+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:24:28.563+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.112 seconds
[2025-05-07T09:24:59.177+0000] {processor.py:157} INFO - Started process (PID=188) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:24:59.178+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:24:59.180+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:24:59.179+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:24:59.213+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:24:59.206+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:24:59.215+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:24:59.256+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.084 seconds
[2025-05-07T09:25:30.226+0000] {processor.py:157} INFO - Started process (PID=193) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:25:30.228+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:25:30.229+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:25:30.229+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:25:30.259+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:25:30.252+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:25:30.262+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:25:30.328+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.108 seconds
[2025-05-07T09:26:01.018+0000] {processor.py:157} INFO - Started process (PID=198) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:26:01.021+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:26:01.023+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:26:01.022+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:26:01.062+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:26:01.053+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:26:01.065+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:26:01.126+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.123 seconds
[2025-05-07T09:26:31.727+0000] {processor.py:157} INFO - Started process (PID=209) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:26:31.730+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:26:31.732+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:26:31.731+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:26:31.760+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:26:31.753+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:26:31.762+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:26:31.820+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.101 seconds
[2025-05-07T09:27:02.498+0000] {processor.py:157} INFO - Started process (PID=220) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:27:02.500+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:27:02.502+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:27:02.502+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:27:02.534+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:27:02.527+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:27:02.536+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:27:02.597+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.106 seconds
[2025-05-07T09:27:33.313+0000] {processor.py:157} INFO - Started process (PID=225) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:27:33.316+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:27:33.319+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:27:33.318+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:27:33.354+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:27:33.347+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:27:33.357+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:27:33.424+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.119 seconds
[2025-05-07T09:28:04.093+0000] {processor.py:157} INFO - Started process (PID=230) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:28:04.096+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:28:04.097+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:28:04.097+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:28:04.131+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:28:04.124+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:28:04.133+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:28:04.184+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.098 seconds
[2025-05-07T09:28:34.841+0000] {processor.py:157} INFO - Started process (PID=241) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:28:34.843+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:28:34.845+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:28:34.845+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:28:34.885+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:28:34.876+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:28:34.888+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:28:34.937+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.104 seconds
[2025-05-07T09:29:05.848+0000] {processor.py:157} INFO - Started process (PID=246) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:29:05.850+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:29:05.851+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:29:05.851+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:29:05.882+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:29:05.875+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:29:05.885+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:29:05.929+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.086 seconds
[2025-05-07T09:29:36.582+0000] {processor.py:157} INFO - Started process (PID=251) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:29:36.585+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:29:36.587+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:29:36.587+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:29:36.636+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:29:36.628+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:29:36.640+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:29:36.737+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.165 seconds
[2025-05-07T09:30:07.375+0000] {processor.py:157} INFO - Started process (PID=256) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:30:07.377+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:30:07.379+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:30:07.379+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:30:07.412+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:30:07.404+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:30:07.415+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:30:07.468+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.102 seconds
[2025-05-07T09:30:38.171+0000] {processor.py:157} INFO - Started process (PID=261) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:30:38.174+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:30:38.176+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:30:38.176+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:30:38.210+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:30:38.203+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:30:38.212+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:30:38.255+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.092 seconds
[2025-05-07T09:31:09.062+0000] {processor.py:157} INFO - Started process (PID=266) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:31:09.065+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:31:09.066+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:31:09.066+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:31:09.094+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:31:09.087+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:31:09.097+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:31:09.131+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.074 seconds
[2025-05-07T09:31:39.906+0000] {processor.py:157} INFO - Started process (PID=271) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:31:39.911+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:31:39.912+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:31:39.912+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:31:39.935+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:31:39.931+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:31:39.936+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:31:39.976+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.085 seconds
[2025-05-07T09:32:10.334+0000] {processor.py:157} INFO - Started process (PID=276) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:32:10.336+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:32:10.337+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:32:10.337+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:32:10.363+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:32:10.358+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:32:10.364+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:32:10.396+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.066 seconds
[2025-05-07T09:32:40.740+0000] {processor.py:157} INFO - Started process (PID=281) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:32:40.742+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:32:40.744+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:32:40.743+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:32:40.783+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:32:40.775+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:32:40.788+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:32:40.829+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.095 seconds
[2025-05-07T09:33:11.167+0000] {processor.py:157} INFO - Started process (PID=286) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:33:11.169+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:33:11.170+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:33:11.170+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:33:11.202+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:33:11.195+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:33:11.205+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:33:11.249+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.088 seconds
[2025-05-07T09:33:41.917+0000] {processor.py:157} INFO - Started process (PID=291) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:33:41.919+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:33:41.921+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:33:41.921+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:33:41.950+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:33:41.943+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:33:41.952+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:33:42.017+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.108 seconds
[2025-05-07T09:34:12.790+0000] {processor.py:157} INFO - Started process (PID=302) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:34:12.792+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:34:12.794+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:34:12.793+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:34:12.832+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:34:12.824+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:34:12.834+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:34:12.874+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.088 seconds
[2025-05-07T09:34:43.562+0000] {processor.py:157} INFO - Started process (PID=307) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:34:43.567+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:34:43.568+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:34:43.568+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:34:43.606+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:34:43.597+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:34:43.610+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:34:43.654+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.113 seconds
[2025-05-07T09:35:14.335+0000] {processor.py:157} INFO - Started process (PID=312) to work on /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:35:14.339+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/fpl_pipeline_dag.py for tasks to queue
[2025-05-07T09:35:14.341+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:35:14.340+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:35:14.369+0000] {logging_mixin.py:150} INFO - [2025-05-07T09:35:14.363+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/fpl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fpl_pipeline_dag.py", line 4, in <module>
    from timedelta import timedelta
ModuleNotFoundError: No module named 'timedelta'
[2025-05-07T09:35:14.371+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/fpl_pipeline_dag.py
[2025-05-07T09:35:14.406+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fpl_pipeline_dag.py took 0.090 seconds
